### ISSUE TITLE
Events API should be compatible with Top limit

### ISSUE THREAD

**Issue by Gimly** [colethecoder/chronological#8]
I'm really confused about the way the limits are supposed to work with the EventsQuery. I can only pass the two limits that implement `INonSortableLimit` (`Sample` and `Take`) in the `EventQuery`method, but I should be able to use a `Top` limit as well.

It's even the example that they are using in the [Query API documentation](
https://docs.microsoft.com/en-us/rest/api/time-series-insights/time-series-insights-reference-queryapi#get-environment-events-streamed-api):

```JSON
{
    "headers" : {
        "Authorization" : "Bearer ... ",
        "x-ms-client-request-id" : "06be6306-..."
    },
    "content" : {
        "searchSpan" : {...},
        "predicate" : {...},
        "top" : {
            "sort" : [{
                "input" : {
                    "builtInProperty" : "$ts"
                },
                "order" : "Asc"
            }],
            "count" : 1000
        }
    }
}
```

As far as I can tell, I can't find any way to recreate this sample using the `EventsQuery` construct. Am I missing something?

**Comment by Gimly** [comment]
Arg, nevermind, I found the override of `EventsQuery` with the sort afterwards... I still find it way too complex to use. IMHO, it should be the same method and the `Limit` object should be responsible for getting the number of elements to take and the sort order, not the `EventQuery` method.

**Comment by colethecoder** [comment]
There are a few places that I'm not entirely happy with the API but I'm reluctant to make breaking changes in V1. What I'd like to do is gather a bit of feedback and then create a V2 which would include tweaks like this and a much better AggregateQuery syntax because the nesting in that is pretty horrific. Before I start focusing on V2 though I want to sort out some performance issues in V1. If you are interested in reviewing performance changes and testing them have a look at that branch, I've made some major improvements so far.

**Comment by Gimly** [comment]
Makes sense, I'll close this issue for now, and I'll take a look at the performance changes.
